"""add workflow_state

Revision ID: 07648b259a0d
Revises: 7b850ab9a48f
Create Date: 2026-10-06 14:26:36.209382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07648b259a0d'
down_revision: Union[str, Sequence[str], None] = '7b850ab9a48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('workflow_state', sa.String(length=30), server_default='NOT_STARTED', nullable=False))
    op.create_index(op.f('ix_customers_consent_status'), 'customers', ['consent_status'], unique=False)
    op.create_index(op.f('ix_customers_workflow_state'), 'customers', ['workflow_state'], unique=False)
    op.add_column('documents', sa.Column('workflow_state', sa.String(length=30), server_default='UPLOADED', nullable=False))
    op.create_index(op.f('ix_documents_workflow_state'), 'documents', ['workflow_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_workflow_state'), table_name='documents')
    op.drop_column('documents', 'workflow_state')
    op.drop_index(op.f('ix_customers_workflow_state'), table_name='customers')
    op.drop_index(op.f('ix_customers_consent_status'), table_name='customers')
    op.drop_column('customers', 'workflow_state')
    # ### end Alembic commands ###
